#!/usr/bin/env python
# -*- coding: utf-8 -*-
from urllib2 import urlopen
from urllib import urlencode
import urllib2
import urllib
import sys
import json

# The google translate API can be found here:
# http://code.google.com/apis/ajaxlanguage/documentation/#Examples
def translate(text = 'hola querida'):
    tl=""
    sl="zh-CN"
    langpair='%s|%s'%(tl,sl)
    #text = text.encode('utf-8', 'ignore')

    base_url='http://ajax.googleapis.com/ajax/services/language/translate?'
    data = urllib.urlencode({'v':1.0, 'ie': 'UTF8', 'q': text, 'langpair':langpair})

    url = base_url+data

    search_results = urllib.urlopen(url)

    d = json.loads(search_results.read())

    result = d['responseData']['translatedText']
    return result

if __name__ == "__main__":
    s = ' '.join(sys.argv[1:])
    print s
    translate(s)
